### ISSUE TITLE
Backgammon licence?

### ISSUE THREAD

**Issue by SamuilDichev** [rlg2161/Backgammon#1]
Hi,

I am doing a Master's in Computer Science and currently working on my project which has to do with creating an AI with a deep neural net for a Backgammon game and I've been looking for a game engine so I don't have to make one myself. 

I noticed you've not set any license and according to this website created with the help of GitHub ( https://choosealicense.com/ ) no license means no rights of use for anybody else including academic usage, such as in my case. 

I was wondering if I could potentially use your game engine to train my AI and if could you please let me know if you intentionally did not include a license. If it is not intentional, the above website can help you choose the right license for your code.

Thank you

**Comment by rlg2161** [comment]
@SamuilDichev -- I've added an MIT License to this project so you can use it freely. Just a heads up the code hasn't been used in a while so you might have to make some updates to interface w/ newer projects + libraries.

**Comment by smdchv** [comment]
Excellent, thanks a lot :)
